version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    network_mode: host
  db:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "./credentials:/root/.config/edgedb/credentials"
      - "db-data:/var/lib/edgedb/data"
    ports:
      - "5656:5656"
    network_mode: host

volumes:
  db-data:
