version: "3.8"

services:
  db:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "./credentials:/root/.config/edgedb/credentials"
      - "db-data:/var/lib/edgedb/data"
    ports:
      - "5656:5656"

volumes:
  db-data:
